services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - PORT=8080
      - BACKEND_PORT=8080
    networks:
      - chat-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:10000"
    expose:
      - "10000"
    depends_on:
      - server
    networks:
      - chat-network
    restart: unless-stopped

networks:
  chat-network:
    driver: bridge
